### ISSUE TITLE
Creating wireframes to develop an interface for login and signup pages

### ISSUE THREAD

**Issue by kovurusaisachin** [kovurusaisachin/AllyGator#1]
#As part of this user-story, we will be creating the wireframes to develop an interface for login and signup pages.

# Estimation of Effort
1 - Day

**Comment by MaitreyiSrinivasan** [comment]
[Login and Signup wireframes.pdf](https://github.com/kovurusaisachin/AllyGator/files/8005294/Login.and.Signup.wireframes.pdf)
